version: "3.8"

services:
  miu:
    build: .
    command: python /miu/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/miu
    ports:
      - 8000:8000

    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --disable-partition-engine-check
    volumes:
      - miu-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: miu
    ports:
      - 3306:3306

volumes:
  miu-mysql-data:
