# Generated by Django 3.1.7 on 2021-03-13 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='next_steps',
            field=models.TextField(null=True),
        ),
    ]
