# Generated by Django 3.1.7 on 2021-03-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_idea_next_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='kind',
            field=models.CharField(choices=[('Vision', 'Vision'), ('Try something', 'Try something'), ('Project', 'Project')], default='Vision', max_length=15),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In progress'), ('Completed', 'Completed')], default='Pending', max_length=11),
        ),
    ]
