# Generated by Django 3.1.7 on 2021-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0003_auto_20210319_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='kind',
            field=models.IntegerField(choices=[(0, 'Vision'), (1, 'Try something'), (2, 'Project')], default=0),
        ),
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'In progress'), (2, 'Completed')], default=0),
        ),
    ]
